### ISSUE TITLE
Fill Out the Readme

### ISSUE THREAD

**Issue by skellet0r** [EthBuilders/social-recovery-wallets#13]
**Is your feature request related to a problem? Please describe.**

When landing on this repository, there isn't any indication of what is used, how the project works, or any other information about this project.

**Describe the solution you'd like**

Filling out the `README.md` will help viewers to understand what the goal of this project is and how to use it.

**Comment by Linda-OC** [comment]
@skellet0r , I am working on this now. I have pushed a READme template to my fork and am in the process of filling out our info.
